language: python
python:
- '3.6'
cache: pip
install:
- pip install scipy
- pip install pytest
- pip install --upgrade lygadgets
- pip install --upgrade lytest
- git clone git@github.com:lukasc-ubc/SiEPIC-Tools.git
- lygadget_link SiEPIC-Tools/klayout_dot_config
script:
- DOCKER=1 pytest tests
